language: go
sudo: false

go:
  - 1.12.x
  - tip

build_matrix:
  allow_failures:
    - tip

script:
  - go test -cover -coverprofile=coverage.txt -covermode="atomic" . -v
  - go test -bench=. -run=. ./bench

after_success:
- bash <(curl -s https://codecov.io/bash)