language: go
sudo: false

go:
  - 1.12.x
  - tip
  
env:
  - GO111MODULE=on

build_matrix:
  allow_failures:
    - tip

script:
  - make test
  - make bench

after_success:
  - bash <(curl -s https://codecov.io/bash)
